id: I348B44F7
default_language: mon
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:35:33.564620
last_modified: 2023-02-10 00:35:33.564807
source_metadata:
  title: 'Śāntideva: Bodhicaryāvatāra'
  language: mon
bases:
  0DA7:
    base_file: 0DA7.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
